### ISSUE TITLE
列表页 跳转到外部链接 是不是新窗口会友好一些

### ISSUE THREAD

**Issue by aa24615** [overtrue/laravel.xyz#4]

**Comment by overtrue** [comment]
其实，这个也有各种答案，比如，我默认当前打开，你想要新窗口打开，安装 cmd(ctrl) 点链接就可以实现新窗口，不过没有一个完美的答案，一些是否关于新窗口打开链接的讨论：

- [在新页面打开窗口好还是原页面打开好？](https://cloud.tencent.com/developer/article/1485441)
- [知乎上你点开一个问题时，常是直接左键打开，还是右键打开新窗口？](http://www.zhihu.com/question/19900305)
- [减少新开窗口提升可访问性](https://link.zhihu.com/?target=http%3A//blog.rexsong.com/%3Fp%3D6063)
- [链接应该在新窗口打开吗？](https://link.zhihu.com/?target=http%3A//goodboy5264.blog.163.com/blog/static/2538298201162122217401/)
- [一个网页如何决定是当前页打开还是新窗口打开？](http://www.zhihu.com/question/20957838)
- [有多少人习惯用鼠标中键点击，在什么情况会用？](http://www.zhihu.com/question/20761491)
- [当前页打开和新窗口打开，你更习惯哪个？](https://www.zhihu.com/question/19641217)
